version: 0.9.9-test_{build}
image: Visual Studio 2017
environment:
  EnableNuGetPackageRestore: true
platform:
- x64
- Mono
configuration:
- Debug
install:
- ps: appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
before_build:
- ps: nuget restore
build:
  verbosity: minimal
for:
-
  matrix:
    only:
      - platform: Mono
    
    after_build:
    - ps: 7z a sabretools_debug-mono-x64.zip C:\projects\Debug-mono-x64\*
    artifacts:
    - path: sabretools_debug-mono-x64.zip
      name: SabreTooks (Mono x64)
for:
-
  matrix:
    only:
      - platform: x64
    
    after_build:
    - ps: 7z a sabretools_debug-x64.zip C:\projects\Debug-x64\*
    artifacts:
    - path: sabretools_debug-x64.zip
      name: SabreTools (x64)
