# version format
version: 1.1.0-test_{build}

# vm template
image: Visual Studio 2019

# environment variables
environment:
  EnableNuGetPackageRestore: true

# msbuild configuration
configuration:
- Debug

# install dependencies
install:
- ps: appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe

# pre-build script
before_build:
- nuget restore

# build step
build:
  verbosity: minimal

# post-build step
after_build:
- cd SabreTools\bin\Debug
- 7z a SabreTools_netcoreapp3.1.zip netcoreapp3.1\*
- 7z a SabreTools_net5.0.zip net5.0\*

- cd ..\..\..\RombaSharp\bin\Debug
- 7z a RombaSharp_netcoreapp3.1.zip netcoreapp3.1\*
- 7z a RombaSharp_net5.0.zip net5.0\*

# testing step
test:
  assemblies:
    - SabreTools.Test.dll

# artifact linking
artifacts:
- path: SabreTools\bin\Debug\SabreTools_netcoreapp3.1.zip
  name: SabreTools (.NET Core 3.1)
- path: SabreTools\bin\Debug\SabreTools_net5.0.zip
  name: SabreTools (.NET 5.0)

- path: RombaSharp\bin\Debug\RombaSharp_netcoreapp3.1.zip
  name: RombaSharp (.NET Core 3.1)
- path: RombaSharp\bin\Debug\RombaSharp_net5.0.zip
  name: RombaSharp (.NET 5.0)