# version format
version: 1.1.0-test_{build}

# vm template
image: Visual Studio 2022

# environment variables
environment:
  EnableNuGetPackageRestore: true

# msbuild configuration
configuration:
- Debug

# install dependencies
install:
- ps: appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe

# pre-build script
before_build:
- nuget restore

# build step
build:
  verbosity: minimal

# post-build step
after_build:
- cd  %APPVEYOR_BUILD_FOLDER%\SabreTools\bin\Debug\net6.0
- 7z a a -tzip %APPVEYOR_BUILD_FOLDER%\SabreTools_net6.0.zip *
- cd  %APPVEYOR_BUILD_FOLDER%\SabreTools\bin\Debug\net7.0
- 7z a a -tzip %APPVEYOR_BUILD_FOLDER%\SabreTools_net7.0.zip *

- cd  %APPVEYOR_BUILD_FOLDER%\RombaSharp\bin\Debug\net6.0
- 7z a a -tzip %APPVEYOR_BUILD_FOLDER%\RombaSharp_net6.0.zip *
- cd  %APPVEYOR_BUILD_FOLDER%\RombaSharp\bin\Debug\net7.0
- 7z a a -tzip %APPVEYOR_BUILD_FOLDER%\RombaSharp.0.zip *

# testing step
test:
  assemblies:
    - SabreTools.Test.dll

# success/failure tracking
on_success:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 success $env:WEBHOOK_URL
on_failure:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 failure $env:WEBHOOK_URL

# artifact linking
artifacts:
- path: SabreTools_net6.0.zip
  name: SabreTools (.NET 6.0)
- path: SabreTools_net7.0.zip
  name: SabreTools (.NET 7.0)

- path: RombaSharp_net6.0.zip
  name: RombaSharp (.NET 6.0)
- path: RombaSharp_net7.0.zip
  name: RombaSharp (.NET 7.0)