# version format
version: 0.9.9-test_{build}

# vm template
image: Visual Studio 2017

# environment variables
environment:
  EnableNuGetPackageRestore: true

# msbuild configuration
platform:
- x64
configuration:
- Debug
- Mono

# install dependencies
install:
- ps: appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe

# pre-build script
before_build:
- nuget restore

# build step
build:
  verbosity: minimal

# post-build step
after_build:
- 7z a sabretools_%CONFIGURATION%-%PLATFORM%.zip C:\projects\Debug*\

# artifact linking
artifacts:
- path: sabretools_$(version)_$(configuration)-$(platform).zip
  name: SabreTools ($(platform))